#!/bin/bash

(curl https://github.com/samchristywork | \
  grep "ContributionCalendar-day" | \
  grep "data-count" | \
  grep "data-date" | \
  awk -F '"' '{print $18, $16}' | \
  grep "`date +%Y-%m-%d`") 2> /dev/null
